# Generated by Django 4.2.1 on 2023-11-05 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(error_messages={'invalid_extension': 'Этот формат не поддерживается!'}, upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'xlsx'))], verbose_name='Файл')),
            ],
        ),
    ]
